Login db
itayHaizler/Tvizugit pull request #78
Opened 2020-05-16 12:34 UTC by rotemhugi

סיימתי את הרישום עם ההתחברות לDB של עורך דין ושל משתמש רגיל
עורך דין נרשם גם לטבלת עורכי דין וגם לטבלה יוזרים עם קישור לרול של עורך דין
משתמש רגיל נרשם רק לטבלת יוזרים עם קישור לרול של משתמש

צריך לעלות את החלק שלי כדי שטלי תוכל להוסיף את החלקים שלה בכל הקבצים החדשים של העורך דין שהוספתי

התחברות עדיין לא עובד 100%, על זה עוד נשאר לי לעבוד

2020-05-16 15:56 UTC, itayHaizler requested changes
יצא לי הרבה תגובות והערות יחסית אבל זה היה המון קבצים וקוד חח אז כל הכבוד על ההשקעה.
תנסי להתחיל ממה שפשוט ואת מבינה ומסתדרת אם את לא מבינה משהו דברי איתי ואם יש משהו שטעיתי או משהו אז אשמח אם תגיבי שאדע :)

2020-05-16 15:56 UTC, itayHaizler commented on client/src/components/login/login.js
> +    //user.displayName = data.UserQueries.user.displayName;
עדיף שלא לדחוף הערות ולוגים

2020-05-16 15:56 UTC, itayHaizler commented on client/src/components/login/login.js
> +    });
את מבקשת את המשתמש עוד לפני שהוא באמת התחבר בצורה הזאת וגם פה ספציפית את לא מבצעת עם זה כלום אז הקטע קוד לא מתאים לכאן

2020-05-16 15:56 UTC, itayHaizler commented on client/src/components/login/profileDetails.js
> +import { useSelector } from 'react-redux';
יכולים להכנס תחת אותו import

2020-05-16 15:56 UTC, itayHaizler commented on client/src/components/login/profileDetails.js
> +    }
עדיף ישר באתחול  להגדיר את המשתנים עם ביטוי טרנרי (ההשמה עם התנאי והסימן שאלה). ככה המשתנה הוא const מוגדר פעם אחת בהתחלה וברור מה עושים איתו.
אבל לפי השימוש שלהם אין צורך בכלל במשתנה אלא אפשר ישר לרשום את הביטוי איפה שאת משתמשת במשתנה.
סתם משהו בכללי לדעתי - אם כבר משתנים הייתי מגדיר את השמות להיות XXXLabel נגיד fullNameLabel, כדי שיהיה ברור שהוא משמש לשמירת הלייבל ולא את השם המלא של המשתמש

2020-05-16 15:56 UTC, itayHaizler commented on client/src/components/login/profileDetails.js
> +        loggedInUser[event.target.name] = event.target.value;
לא אמורים לערוך בloggedInUser את המידע, המטרה שנקבל את הפרטים המאומתים מהשרת כשמתחברים ואז נשמור אותם במשתנה הזה, לא אמורים לשנות בתוכו את הערכים אלא אם כן משתמש התחבר ואז מקבלים את המידע עליו מהשרת.
את המידע שאת עורכת ומשנה בדף הזה תנהלי במשתנה אחר בstate האישי של הקומפוננטה.

2020-05-16 15:56 UTC, itayHaizler commented on client/src/components/login/profileDetails.js
> +        else if ( reg.test(loggedInUser.email) === false ){
אפשר פשוט להשתמש באופרטור '!' בלי להשוות לfalse.

2020-05-16 15:56 UTC, itayHaizler commented on client/src/components/login/profileDetails.js
> +            if(password1 !== undefined){
אם את רוצה לבדוק אם משתנה הוא undefined או במקרה הזה שהוא לא, מספיק לרשום בתנאי את שם המשתנה (במקרה הזה עם אופרטור '!').
לצורך העניין: 
if(!password1)

2020-05-16 15:56 UTC, itayHaizler commented on client/src/components/login/registerLawyerOffice.js
> +    const loggedInLawyer = useSelector(state => state.lawyer.loggedInLawyer)
למה אנחנו מנהלים 2 משתנים על משתמש מחובר?
לא חושב שצריך שתהיה הפרדה ביניהם, למשתמש שמחובר יש מידע האם הוא עו"ד וזה מספיק כדי למדר עמודים ופיצ'רים במערכת.
פרטים על עו"ד צריך רק כשיהיה בהם צורך במסך.
לא חושב שצריך משתנה כזה בstore הכללי.

2020-05-16 15:56 UTC, itayHaizler commented on client/src/components/login/registerLawyerOffice.js
> +            addNewLawyer({
אני לא חושב שפעולת רישום של עו"ד לא צריכה להיות מפוצלת בשתי בקשות שונות.
אין שום מזהה חח"ע שמקשר בין 2 הבקשות האלה גם.
צריך ברגע שרושמים את המשתמש לקשר אותו למשרד שלו דרך הID אם זה משהו ששומרים בdocument נפרד.

2020-05-16 15:56 UTC, itayHaizler commented on client/src/components/navbar/navbar.js
> +  const show = mode === "connected" ?
לא צריך משתנה כזה (או אופציה כזאת של connected יותר נכון כי את משתמש בmode לעוד דברים) ובדיקה כזאת, אם המשתמש מחובר פשוט צריך לבדוק האם האובייקט loggedInUser לא ריק.

2020-05-16 15:56 UTC, itayHaizler commented on client/src/store/lawyer.js
> +function lawyerReducer(state = initialState, action) {
בהתאם למה שרשמתי מקודם לגבי loggedInLawyer, אין צורך במשתנה הזה וגם בreducer כרגע לפחות.

2020-05-16 15:56 UTC, itayHaizler commented on client/src/store/user.js
> +  },
המשתנה צריך להיות מאותחל לאובייקט ריק כמו מקודם ולהשתמש בו כמו שהצעתי באחת ההערות הקודמות.
בשביל השימוש של הרישום והכל צריך משתנה ספצפי בstate של אותה קומפוננטה

2020-05-16 15:56 UTC, itayHaizler commented on server/src/models/Lawyer/lawyerQueries.js
> +        _id: { type: GraphQLString },
המקף התחתון שליד הid מיותר, אנחנו יכולים להשתמש פשוט ב"id".
זה סתם צורת כתיבה של מונגוס שרושם ככה לid שהוא מייצר שלא תתבלבלי ותשתמשי בזה סתם

2020-05-16 15:56 UTC, itayHaizler commented on server/src/models/Lawyer/lawyerSchema.js
> +    type: String,
הטיפוס צריך להיות רשימה של classActions.
יכולה להסתכל באחד המודלים האחרים איך הגדרנו מאפיין שהוא אובייקט מטבלה חיצונית.

2020-05-16 15:56 UTC, itayHaizler commented on server/src/models/User/UserType.js
> +    _id: { type: GraphQLString },
כנל כאן לגבי המקף התחתון

2020-05-16 15:56 UTC, itayHaizler commented on server/src/models/User/UserType.js
> +    role: { type: GraphQLString },
למה שינית את הtype למחרוזת?

2020-05-16 15:56 UTC, itayHaizler commented on server/src/models/Lawyer/lawyerType.js
> +    img: { type: GraphQLString },
בסוף לא הבנתי מהקבוצה כי ההודעה שלי נעלמה בין כל ההודעות חחחח
איפה נשמרת התמונה לא ראיתי התייחסות לזה בקוד, צריך לבחור צורה טובה ונוחה לעשות את זה

2020-05-16 15:56 UTC, itayHaizler commented on server/src/models/User/userModel.js
> +  },
גם כאן שינית את role ומחקת את הref שהגדרתי, זה בטעות? אם כן אז כדאי לתקן את זה אחרת יהיו באגים.

2020-05-16 15:56 UTC, itayHaizler commented on server/src/models/User/userQueries.js
> +        role: {type: GraphQLString}
זה בסדר שהם לא חובה, אבל למה הוספת כל כך הרבה פרמטרים, אני לא חושב שנשלוף משתמש לפי displayName או role לצורך העניין.

2020-05-17 09:59 UTC, rotemhugi commented on client/src/components/login/login.js
> +    //user.displayName = data.UserQueries.user.displayName;
כן עשיתי את זה בשביל ההתחברות שעדיין לא עבדה לי
אני לא אשאיר את זה שם אחרי שההתחברות תעבוד.
בינתיים שמתי גם את הconsole.log בהערה

2020-05-17 10:01 UTC, rotemhugi commented on client/src/components/login/login.js
> +    });
נכון, זה אמור להיות בתוך הפונקציה של ההתחברות אבל משום מה הוא הביא לי על זה שגיאה אז העברתי את זה לאיפה שזה עכשיו ואז זה כן עבד.

כמו ההערה הקודמת - זה חלק שרלוונטי להתחברות שלא עובד כרגע.
אז מככבת גם את החלק הזה בינתיים

2020-05-17 10:37 UTC, Talicohen123 commented on server/src/models/Lawyer/lawyerType.js
> +    img: { type: GraphQLString },
מסכימה עם הייזלר, דיברנו על זה שהאובייקט במונגו צריך להיות binary אבל אל בטוחה בצד שרת עוד איך זה בא לידי ביטוי

2020-05-17 18:50 UTC, rotemhugi commented on client/src/components/login/profileDetails.js
> +    }
תודה!
שיניתי :)

2020-05-17 18:54 UTC, rotemhugi commented on client/src/components/login/profileDetails.js
> +        loggedInUser[event.target.name] = event.target.value;
לא מסכימה, בסופו של דבר אני שומרת את המשתמש שנרשם בדיוק לפי הערכים שהוא הכניס
מיותר ליצור משתנה חדש של יוזר רק לרישום
זה ממש כפל קוד
הוא באמת הופך להיות ה-loggedInUser אחרי שהוא נרשם וכל הפרטים שמוכנסים שם הם אמיתיים מהDB כי הוא הרגע הכניס.

2020-05-17 18:55 UTC, rotemhugi commented on server/src/models/Lawyer/lawyerType.js
> +    img: { type: GraphQLString },
כרגע זה עדיין string
בהמשך נשנה לבינארי או כל מה שנחליט

2020-05-17 18:57 UTC, rotemhugi commented on server/src/models/User/userModel.js
> +  },
שיניתי כי זה לפי הDB
בDB הרול הוא STRING
ולא מבנה

למה אתה צריך את כל המבנה?

2020-05-17 18:58 UTC, rotemhugi commented on server/src/models/User/userQueries.js
> +        role: {type: GraphQLString}
לא חייב לשלוף את כל השדות, הוספתי את כולם כי אני צריכה אותם בשביל הרישום משתמש

2020-05-17 18:59 UTC, rotemhugi commented on server/src/models/User/UserType.js
> +    role: { type: GraphQLString },
אתה שואל לגבי הROLE?
עניתי גם בהודעה הנוספת שכתבת, בDB הרול הוא STRING אז לפי זה 
וזה קיים בשביל השמירה לDB של יוזר חדש

2020-05-17 19:00 UTC, rotemhugi commented on client/src/components/login/profileDetails.js
> +import { useSelector } from 'react-redux';
הכנסתי

2020-05-17 19:00 UTC, rotemhugi commented on server/src/models/User/UserType.js
> +    _id: { type: GraphQLString },
מה לגבי הקו התחתון?
שהוא מיותר?

2020-05-17 19:03 UTC, rotemhugi commented on client/src/components/login/profileDetails.js
> +        else if ( reg.test(loggedInUser.email) === false ){
תיקנתי

2020-05-17 19:12 UTC, rotemhugi commented on client/src/components/login/profileDetails.js
> +            if(password1 !== undefined){
לא נכון, זה בדיוק הפוך
נכון לכתוב if(!password1)
במקום השוואה לundefined:
password1 === undefined
ולא הפוך
שיניתי במקומות שעשיתי השוואה ל undefined ובדקתי שזה באמת עובד כמו שצריך

2020-05-17 19:14 UTC, rotemhugi commented on client/src/components/login/registerLawyerOffice.js
> +    const loggedInLawyer = useSelector(state => state.lawyer.loggedInLawyer)
יהיה צורך בהמשך לשלוף פרטים על המשרד שלו -
לדוגמא כדי להציג את דרכי יצירת קשר בעמוד שלו 
ואז יהיה ניתן לשמור בstate את הפרטים האלו

2020-05-17 19:15 UTC, rotemhugi commented on client/src/components/login/registerLawyerOffice.js
> +            addNewLawyer({
אני וטלי דיברנו על זה,
יש את המייל ואת שם המשרד שזה נתון שנשמר בשניהם
ספציפית המייל הוא יהיה המזהה המקשר כי לא ניתן לרשום 2 משתמשים שונים עם אותו מייל
אז זה פותר את הבעיה

2020-05-17 19:20 UTC, rotemhugi commented on client/src/components/navbar/navbar.js
> +  const show = mode === "connected" ?
לא נכון, הloggedInUser יהיה מלא גם אם המשתמש עדיין לא באמת נרשם
לדוגמא אחרי השלב הראשון של הרישום של עורך דין
אני משנה את הMODE רק לאחר שהוא נרשם
וגם ככה מה שאני משנה זה את השם המלא שמופיע במקום הכפתור
אז זה בהכרח יהיה כשסיימו את המסכי הרישום

2020-05-17 19:22 UTC, rotemhugi commented on client/src/store/lawyer.js
> +function lawyerReducer(state = initialState, action) {
לא מסכימה
צריך לשמור את הפרטים האלה
הרחבתי בתגובה אחרת שלי

2020-05-17 19:23 UTC, rotemhugi commented on client/src/store/user.js
> +  },
לא מסכימה
זה כפל קוד מיותר
בסוף היוזר שנרשם הוא הופך להיות ה-loggedInUser
לכן זה כן נכון שאני מכניסה אותו שם

2020-05-17 19:26 UTC, rotemhugi commented on server/src/models/Lawyer/lawyerQueries.js
> +        _id: { type: GraphQLString },
שיניתי

2020-05-17 19:28 UTC, rotemhugi commented on server/src/models/Lawyer/lawyerSchema.js
> +    type: String,
שמרתי הכל כstring
זה כמובן ישתנה בהמשך

2020-05-17 19:29 UTC, rotemhugi commented on server/src/models/Lawyer/lawyerSchema.js
> +    type: String,
לא מצאתי דוגמא לשמירה של רשימה
אשמח שתגיד לי איפה להסתכל

2020-05-17 19:29 UTC, rotemhugi commented on server/src/models/User/UserType.js
> +    _id: { type: GraphQLString },
הורדתי

2020-05-17 20:39 UTC, rotemhugi commented on server/src/models/User/UserType.js
> +    role: { type: GraphQLString },
החזרתי את הROLE להיות כמו קודם

2020-05-17 20:41 UTC, rotemhugi commented on server/src/models/User/userModel.js
> +  },
שיניתי את הROLE למה שהיה קודם

2020-05-18 09:02 UTC, itayHaizler commented on client/src/components/login/login.js
> +    });
זה לא עבד כי אי אפשר להשתמש בuseQuery רק בתנאי מסוים או בתוך פונקציות שהן לא הקומפוננטה עצמה.
אפשר לבצע בקשה שלא דרך useQuery או useMutation בעזרת הclient שייחצנתי מapolloService.js בתיקיית utils.
יכולה לראות איך משתמשים בדוקומנטציה שלהם ויש גם דוגמא לזה אצלינו בreducer של classAction בפונקציה של הDELETE.

2020-05-18 09:12 UTC, itayHaizler commented on client/src/components/login/profileDetails.js
> +            if(password1 !== undefined){
כנראה לא הבנתי אותי כי לא הבנתי אותך חח. נראה שכתבת בדיוק מה שכתבתי אבל בקוד לא עשית ככה.
אמרתי שלא נכון להשוות לundefined עם === או !=== אלא פשוט לרשום את שם האובייקט עם '!'
ז"א במקום:
if(password !== undefined) 
לרשום:
if (password)

2020-05-18 09:30 UTC, itayHaizler commented on client/src/components/login/registerLawyerOffice.js
> +    const loggedInLawyer = useSelector(state => state.lawyer.loggedInLawyer)
הבנתי.
אז שוב כמו שאמרתי אין צורך לשמור אותו בstore, ולא צריך לשמור loggedInLawyer.
זה משהו ששולפים איפה שצריך, לא שומרים את כל המידע בstore זה לא המטרה שלו.
את צריכה להשתמש רק בstate האישי של הקומפוננטה פה

2020-05-18 09:35 UTC, itayHaizler commented on client/src/components/login/registerLawyerOffice.js
> +            addNewLawyer({
כן האמת יצא לי לדבר על זה עם טלי אתמול, שנכון שזה מייחד את שניהם וכביכול מקשר, אבל אין קישור אמיתי בין שניהם בשרת.
בכל אופן אם עו"ד נרשם ישר כעו"ד וכיוזר, אז זה צריך לקרות ביחד ואולי אפשר וכדאי לצמצם בקשות.

וחשבתי שאולי כדאי שיהיה קישור של מאפיין חיצוני בdocument שמקשר בין היוזר לעו"ד ישירות (זה די מוזר אצלינו ההפרדה ביניהם אז את זה אני סתם מעלה כרעיון אם את חושבת שזה יקל ויעזור כרגע)

2020-05-18 09:37 UTC, itayHaizler commented on client/src/components/navbar/navbar.js
> +  const show = mode === "connected" ?
את משתמשת לא נכון אז בloggedInUser והסברתי גם איפה שהשתמשת בו מה צריך לעשות במקום)
צריך להיות לו שימוש ומשמעות אחידה ולא לערוך עליו דברים.
אם יוזר התחבר יהיה בו מידע ורק כשהוא התחבר, אחרת הוא יהיה אובייקט ריק, במה שאת השתמשת בו את צריכה לעבוד על אובייקט מקומי במקום.

2020-05-18 09:41 UTC, itayHaizler commented on client/src/store/user.js
> +  },
זה שהוא הופך בסוף להיות מחובר (אגב זה גם לא בטוח כי יכול להיות שבסוף תהיה בעיה או שגיאה והוא לא נרשם) זה לא סיבה, כמו שרשמתי בהערות אחרות צריכה להיות לו משמעות אחת ואת העריכה שלך לעשות על אובייקט אחר.
אם צריך נעשה על זה שיחה ונעבור על מה שלא ברור/מוסכם ביחד

2020-05-18 09:51 UTC, itayHaizler commented on server/src/models/Lawyer/lawyerSchema.js
> +    type: String,
זה דברים שכבר מימשנו ולא בעיה לסדר, זה פשוט לא יעבוד טוב אם נשאיר את זה ככה.
יכולה להסתכל בclassActionSchema נגיד בusers

2020-05-18 09:56 UTC, itayHaizler commented on server/src/models/User/userQueries.js
> +        role: {type: GraphQLString}
כן ברור לי שלא חובה להשתמש בכולם, אבל כאן את מגדירה איזה פרמטרים את מקבלת בשביל לשלוף את הuser, את לא צריכה את כל הפרמטרים האלה (לצורך העניין אלה שרשמתי למעלה) וגם ככה בפעולה של חיפוש לא משתמשים בהם

2020-05-18 10:17 UTC, itayHaizler commented on server/src/models/User/userModel.js
> +  },
כי ככה אפשר לשלוף את המידע של הrole שלו ישר בשליפה.
בקיצור זה היה מסיבה מסוימת שכתבתי את זה ככה חח

2020-05-18 15:16 UTC, rotemhugi commented on client/src/components/login/profileDetails.js
> +            if(password1 !== undefined){
חח אוקיי עכשיו נראה לי שהבנתי
שיניתי

2020-05-18 15:31 UTC, rotemhugi commented on server/src/models/Lawyer/lawyerSchema.js
> +    type: String,
type: Schema.Types.ObjectId, ref: "user" 
ככה רק במקום user לכתוב classaction?

2020-05-22 11:11 UTC, rotemhugi commented on client/src/components/login/profileDetails.js
> +        loggedInUser[event.target.name] = event.target.value;
הוספתי מבנה חדש בstore כמו שדיברנו
של registerUser

2020-05-22 11:11 UTC, rotemhugi commented on server/src/models/User/userQueries.js
> +        role: {type: GraphQLString}
ירדו

2020-05-22 11:11 UTC, rotemhugi commented on client/src/components/login/registerLawyerOffice.js
> +    const loggedInLawyer = useSelector(state => state.lawyer.loggedInLawyer)
הוספתי regiserUser כמו שדיברנו

2020-05-22 11:12 UTC, rotemhugi commented on client/src/components/login/registerLawyerOffice.js
> +            addNewLawyer({
נשאר עדיין 2 פעולות 
מקסימום בהמשך אאחד אותם

2020-05-22 11:12 UTC, rotemhugi commented on client/src/store/lawyer.js
> +function lawyerReducer(state = initialState, action) {
שיניתי לregisterLawyer כמו שדיברנו

2020-05-22 11:13 UTC, rotemhugi commented on client/src/store/user.js
> +  },
הוספתי registerUser
שמתאחד עם הloggedinuser אחרי שהוא סיים להרשם

2020-05-22 11:13 UTC, rotemhugi commented on server/src/models/Lawyer/lawyerSchema.js
> +    type: String,
שיניתי את זה למה שדיברנו ופתאום לא עבד לי ההוספה של העורך דין לDB
אז החזרתי להיות כמו עכשיו
מקסימום בהמשך נשנה

2020-05-22 11:14 UTC, rotemhugi commented on client/src/components/navbar/navbar.js
> +  const show = mode === "connected" ?
שיניתי לבדיקה האם לערך displayname מתוך הloggedinuser יש ערך

2020-05-22 13:25 UTC, itayHaizler approved these changes

2020-05-22 13:25 UTC, merged